### PR TITLE
Added resource page

### LINKED ISSUE #95: Interesting Reads / Articles / Information page
The current ways to share related articles, videos, etc are : News feed, recent articles and the "interesting reads" section.
All three are rather unstructured and the first two are "rolling". The "interesting reads" is limited to 5 links.

I believe in the meantime, we have enough content out there to create a community maintained page to add related resources (articles and videos) about ECDTools topics in a structured way, e.g. per project and some generic sections.

I believe this would help visitors in gaining information and get a structured overview.

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #95

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Comment by autumnfound** [comment]
This is at around 800px width I think it was, we may want to consider nesting or removing a few items to avoid spillover.
image

**Comment by JonasHelming** [comment]
> This is at around 800px width I think it was, we may want to consider nesting or removing a few items to avoid spillover.
> image
personally, I think 1024 is the absolute minmum to consider, but I have opened https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/115 for dicussion

**Comment by JonasHelming** [comment]
@autumnfound : Are you fine with solving your comment in the other issue?

**Comment by JonasHelming** [comment]
@autumnfound

**Comment by JonasHelming** [comment]
@chrisguindon

**Comment by autumnfound** [comment]
Apologies @JonasHelming ! This got lost in the pile, I'll merge it in now. We can look at getting the menu sorted tomorrow to get this up

**Review by autumnfound — APPROVED** [review]

**Pull request merged**
