### PR TITLE
 add featured story

### PR DESCRIPTION
**Pull request by flora8984461**
Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by autumnfound — APPROVED** [review]

**Comment by flora8984461** [comment]
@chrisguindon  Actually, these sites put their "Stay connected" on all pages, should I do this too? 🤔

**Comment by brianking** [comment]
I'm missing the context around this PR!

**Comment by flora8984461** [comment]
> I'm missing the context around this PR!

Hello Brian @brianking , this is to update the theme version to the latest so that we can add featured story or footer through newsletter.eclipse.org instead of adding it in a file. I think this is also the marketing team's goal @chrisguindon

**Comment by flora8984461** [comment]
> @chrisguindon Actually, these sites put their "Stay connected" on all pages, should I do this too? 🤔

updated, added partial (footer_custom) instead.

**Comment by chrisguindon** [comment]
@brianking You can find the context for this here:
https://github.com/EclipseFdn/jquery-eclipsefdn-api/issues/16

This is something that we are installing across all our WG sites in order to allow the MKT to promote stuff without having to submit a PR to each website.

**Comment by brianking** [comment]
Great thanks

**Pull request merged**
