### PR TITLE
Define website look and feel (imagery) #1

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by ChristieWittEclipse** [comment]
@chrisguindon everything looks great. Here is my feedback:
-Update the favicon to the one I provided, for some reason I still see the generic Eclipse Foundation one.
-Please add the Founding member logos
-Double check that the color pallet has been updated to the colors I provided. For example, the ".featured-section h2" class is using a blue color but I didn't provide a blue below:
@brand-primary: #F89521; // Light orange
@brand-secondary: #B15B27; // Dark Orange
@brand-tertiary: #2C2255; // Dark Purple
@brand-quaternary: #efefef; // Light Gray

**Comment by chrisguindon** [comment]
> -Update the favicon to the one I provided, for some reason I still see the generic Eclipse Foundation one.
Done! 
> -Please add the Founding member logos
This will be done via https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/3

> -Double check that the color pallet has been updated to the colors I provided. For example, the ".featured-section h2" class is using a blue color but I didn't provide a blue below:
> @brand-primary: #F89521; // Light orange
> @brand-secondary: #B15B27; // Dark Orange
> @brand-tertiary: #2C2255; // Dark Purple
> @brand-quaternary: #efefef; // Light Gray

It should be fine now! You can verify here:
https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/51fa297109e0e203ab8f0f38ee9796d5a64e204d/less/_variables.less

**Comment by ChristieWittEclipse** [comment]
+1 looks great, I will review with Thabang and let you know if any further updates are needed.

**Comment by chrisguindon** [comment]
@ChristieWittEclipse thanks! Great job  on the look and feel!

**Pull request merged**
