### PR TITLE
Embedded SIG blog post

### PR DESCRIPTION
**Pull request by brianking**
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>

### CODE REVIEW

**Comment by ericpoirier** [comment]
@brianking would it be possible to get smaller (optimized) images, they are pretty big. One of the is 24MB.

**Comment by brianking** [comment]
> @brianking would it be possible to get smaller (optimized) images, they are pretty big. One of the is 24MB.

Potentially. I already changed the dimensions of that animated gif. Because it has 62 frames, it didn't reduce the file size too much. Any ideas how to do this without sacrificing visual quality?

**Comment by ericpoirier** [comment]
> > @brianking would it be possible to get smaller (optimized) images, they are pretty big. One of the is 24MB.
> 
> Potentially. I already changed the dimensions of that animated gif. Because it has 62 frames, it didn't reduce the file size too much. Any ideas how to do this without sacrificing visual quality?

For example the 24MB gif is 1239x873px. This is way bigger than needed. The image shouldn't be bigger than the container which is 877px. You could also remove some frames to reduce the size.

**Comment by brianking** [comment]
@MatthewKhouzam Might you be able to help out here, in terms of providing a smaller gif (both dimensions limited to, say, 800px width and file size)?

**Comment by brianking** [comment]
@ericpoirier I just committed again, PR should now be up to date. GIF file has smaller dimensions and is now down to 17MB. Is that still too big?

**Comment by ericpoirier** [comment]
> @ericpoirier I just committed again, PR should now be up to date. GIF file has smaller dimensions and is now down to 17MB. Is that still too big?

Hi Brian, sorry for the wait but after discussion with Chris, 12MB is still too big. Ideally a 2MB gif would be the max we would allow.

An alternative would be to create a video and update it to youtube, this way the page will load fast.

**Comment by brianking** [comment]
@ericpoirier Would another alternative just be to have a quick loading static image and then just link to the animation (also hosted in the images folder)?

**Comment by brianking** [comment]
> @ericpoirier Would another alternative just be to have a quick loading static image and then just link to the animation (also hosted in the images folder)?

I've implemented this solution.

**Pull request merged**
