### PR TITLE
#148 - Update the layout of the adopters page

### PR DESCRIPTION
**Pull request by ericpoirier**
#148 

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by ericpoirier** [comment]
We have the +1 from Clark.

**Review by autumnfound — CHANGES_REQUESTED** [review]
I'm not sure that duplicating the adopters js file is the best solution here. Is there a reason why you're just changing it to a p tag instead of a list?

**Comment by ericpoirier** [comment]
> I'm not sure that duplicating the adopters js file is the best solution here. Is there a reason why you're just changing it to a p tag instead of a list?

I'm copying some of the code that was done before the layout of the adopters page is changing entirely for ECDtools.

When Chris and I talked about this, we decided to do so and if the layout is working well we will probably want to move it over to solsitce-assets and hugo theme.

**Comment by chrisguindon** [comment]
> > I'm not sure that duplicating the adopters js file is the best solution here. Is there a reason why you're just changing it to a p tag instead of a list?
> 
> I'm copying some of the code that was done before the layout of the adopters page is changing entirely for ECDtools.
> 
> When Chris and I talked about this, we decided to do so and if the layout is working well we will probably want to move it over to solsitce-assets and hugo theme.

I think this new layout should become our default implementation. We are lucky that we only have 2 sites with an adopters page.

I am fine with a temporary solution like this once since we do have quite a few projects to deliver before Christmas.

 However, I want to see an issue created in solstice-assets to migrate this work to solstice-assets and our Hugo base theme.

**Review by autumnfound — APPROVED** [review]
I'll create a tech debt item for this, but good to go!

**Pull request merged**
