### PR TITLE
Add CDT cloud to list of projects categories

### LINKED ISSUE #233: Filter buttons not working on category page
On this page: https://ecdtools.eclipse.org/projects/
The buttons to "Filter by category" do not appear to be working.
When you click on a button, nothing happens. The project tiles should sort according to the button that is clicked.
There is an error that appears in the console as well, screenshot below.
This is using Google Chrome on Windows, and I was able to reproduce in Microsoft Edge and Firefox as well.

Screenshot 2022-03-24 115603

### PR DESCRIPTION
**Pull request by ericpoirier**
Fixes #233 

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by croundy** [comment]
> @croundy in order to fix the "undefined" issue I need to add CDT Cloud's category to the list. Can you validate that i'm using the proper category for this project?
> 
> Thanks.

@ericpoirier sorry, I'm having a hard time following this issue. What exactly is the category to which CDT Cloud is being added?

**Comment by ericpoirier** [comment]
> > @croundy in order to fix the "undefined" issue I need to add CDT Cloud's category to the list. Can you validate that i'm using the proper category for this project?
> > Thanks.
> 
> @ericpoirier sorry, I'm having a hard time following this issue. What exactly is the category to which CDT Cloud is being added?

On the following page:

https://ecdtools.eclipse.org/projects/

In the blue bar of the Eclipse CDT.cloud project, it says "undefined" because this project was not attributed a category which is what my PR is doing.

Also when a project's category is undefined, it breaks the Filters.

That being said, I need to make some changes to my PR so that when a project's category is "undefined", I should hide the blue bar.

**Comment by ericpoirier** [comment]
@croundy let me know if that makes sense.

**Comment by ericpoirier** [comment]
> @ericpoirier ok I see. Thanks for the clarification. I'm thinking that we should add another category. Perhaps just "Other Tools" as a catch all for anything that doesn't have a specific category. I'm also thinking that some of the other projects may be miscategorized and/or we need to do some tweaking in general to the categories. Let me think on that and talk to @kineticsquid about how we might improve how we categorize the projects. Thanks!

Ok sounds good I can change that.

When a project's category is not yet defined, should they be automatically assigned to "Other Tools"?

**Comment by croundy** [comment]
> Ok sounds good I can change that.
> 
> When a project's category is not yet defined, should they be automatically assigned to "Other Too

Yes, let's do that just to avoid having filter issues. Thanks @ericpoirier!

**Comment by chrisguindon** [comment]
PR migrated to GL: https://gitlab.eclipse.org/eclipsefdn/it/websites/ecdtools.eclipse.org/-/merge_requests/234

**Pull request closed without merging**
