### PR TITLE
Update the design of the About page

### PR DESCRIPTION
**Pull request by ericpoirier**
Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
image

Is this intentional? It seems a little funky for the background to be so small on tablet bp

**Comment by brianking** [comment]
In general, the text in the About and FAQ sections looks a bit small to me. Not vs the design, but in general.

**Comment by autumnfound** [comment]
> In general, the text in the About and FAQ sections looks a bit small to me. Not vs the design, but in general.

If you're looking at that screenshot, its zoomed out so that I can more easily capture stuff. Otherwise, that text is the same size as on our internal pages such as https://www.eclipse.org/org/workinggroups/

**Comment by croundy** [comment]
It looks like a bunch of t's and i's are missing throughout the page. I would say we forgot to dot our i's and cross our t's, but they are actually not even there.

Also, anywhere is it says Eclipse Cloud Development Tools should be shortened to Eclipse Cloud DevTools. Looks like we missed one instance on the final FAQ

**Comment by ericpoirier** [comment]
> image
> 
> Is this intentional? It seems a little funky for the background to be so small on tablet bp

No its not, I was not entirely done with the PR, but thanks for pointing it out.

**Comment by ericpoirier** [comment]
> It looks like a bunch of t's and i's are missing throughout the page. I would say we forgot to dot our i's and cross our t's, but they are actually not even there.
> 
> Also, anywhere is it says Eclipse Cloud Development Tools should be shortened to Eclipse Cloud DevTools. Looks like we missed one instance on the final FAQ

I copy/pasted the text from the PDF. If you know where I could get a text copy of the pages, that would be great. Thanks.

**Comment by ericpoirier** [comment]
> > > It looks like a bunch of t's and i's are missing throughout the page. I would say we forgot to dot our i's and cross our t's, but they are actually not even there.
> > > Also, anywhere is it says Eclipse Cloud Development Tools should be shortened to Eclipse Cloud DevTools. Looks like we missed one instance on the final FAQ
> > 
> > 
> > I copy/pasted the text from the PDF. If you know where I could get a text copy of the pages, that would be great. Thanks.
> 
> @ericpoirier I'm looking at the PDF and it doesn't seem to be missing these letters, except for a couple of typos I see. We didn't create a text version for every page as much of this was done collaboratively with Excentric. If needed, I can create a G Doc for the page, but before doing so wanted to see if there is another option for you to pull the text directly from the PDF and ensure content integrity?

I tried exporting the text using 3rd party tools and it still doesn't work. I'm getting the text with missing characters all the time. It would be best to get a text file containing all the content.

Thanks.

**Comment by croundy** [comment]
> > > > It looks like a bunch of t's and i's are missing throughout the page. I would say we forgot to dot our i's and cross our t's, but they are actually not even there.
> > > > Also, anywhere is it says Eclipse Cloud Development Tools should be shortened to Eclipse Cloud DevTools. Looks like we missed one instance on the final FAQ
> > > 
> > > 
> > > I copy/pasted the text from the PDF. If you know where I could get a text copy of the pages, that would be great. Thanks.
> > 
> > 
> > @ericpoirier I'm looking at the PDF and it doesn't seem to be missing these letters, except for a couple of typos I see. We didn't create a text version for every page as much of this was done collaboratively with Excentric. If needed, I can create a G Doc for the page, but before doing so wanted to see if there is another option for you to pull the text directly from the PDF and ensure content integrity?
> 
> I tried exporting the text using 3rd party tools and it still doesn't work. I'm getting the text with missing characters all the time. It would be best to get a text file containing all the content.
> 
> Thanks.

No worries. For the About page, I pulled everything out of the pdf and put it in a G doc here: https://docs.google.com/document/d/1YnJfk-gY0dsy_igMwPW4y0FOxalm_rXIga7vhgMoa_k/edit

**Comment by ericpoirier** [comment]
Thanks Clark for providing the text, I added that in my latest commit.

**Comment by ericpoirier** [comment]
I'll merge this PR to the redesign-2021 branch so I can continue working on other sub pages but let me know if you'd like to make more changes to this page.

Thanks!

**Comment by croundy** [comment]
@ericpoirier there were a few minor changes to the "About" text. Here's the updated document. 

https://docs.google.com/document/d/1YnJfk-gY0dsy_igMwPW4y0FOxalm_rXIga7vhgMoa_k/edit

**Pull request merged**
