### PR TITLE
Reordered the menu items

### PR DESCRIPTION
**Pull request by linkfang**
For [issue115](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/115)

### CODE REVIEW

**Comment by JonasHelming** [comment]
The PR removes this sub page: https://github.com/EclipseFdn/ecdtools.eclipse.org/pull/114

**Comment by autumnfound** [comment]
Good catch @JonasHelming ! This page seems to capture Project resources, how does that sound for a heading?

**Comment by JonasHelming** [comment]
sounds good!

**Comment by linkfang** [comment]
Hi @JonasHelming , how does it look now?

**Comment by linkfang** [comment]
Hi @JonasHelming , 

Now the menu item name is "Resources", please preview here:
https://deploy-preview-132--eclipsefdn-ecdtools.netlify.app/?utm_source=github&utm_campaign=bot_dp

**Review by autumnfound — APPROVED** [review]

**Pull request merged**
